# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apePaterno', models.CharField(max_length=60)),
                ('apeMaterno', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='DetalleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=15)),
                ('precioUni', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'detalleMenu',
                'verbose_name_plural': 'detalleMenus',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(max_length=100)),
                ('maxPersonas', models.CharField(max_length=60)),
                ('numMesa', models.CharField(max_length=60)),
                ('libre', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.CharField(max_length=10)),
                ('servido', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cliente')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Menu')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipoProducto', models.CharField(max_length=15)),
                ('uniMedida', models.CharField(max_length=15)),
                ('cantidad', models.CharField(max_length=60)),
                ('precio', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizada', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cliente')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Mesa')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=15)),
                ('precioTotal', models.FloatField(default=0.0)),
                ('pagado', models.CharField(max_length=15)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Menu')),
                ('Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Pedido')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.AddField(
            model_name='detallemenu',
            name='Menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Menu'),
        ),
    ]
