# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='catalogo.Categoria', verbose_name='list of Categorias'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.UnidadMed'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
    ]
