# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20171026_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='person',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_med',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='UnidadMed',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
