# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_menu_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=15)),
                ('precioUni', models.FloatField(default=0.0)),
                ('precioTotal', models.FloatField(default=0.0)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Menu')),
                ('Venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Venta')),
            ],
            options={
                'verbose_name': 'detalleVenta',
                'verbose_name_plural': 'detalleVentas',
            },
        ),
        migrations.RemoveField(
            model_name='detallemenu',
            name='Menu',
        ),
        migrations.DeleteModel(
            name='DetalleMenu',
        ),
    ]
