# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20171030_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'verbose_name': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipoProducto', models.CharField(max_length=15)),
                ('uniMedida', models.CharField(max_length=15)),
                ('cantidad', models.CharField(max_length=60)),
                ('precio', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
            },
        ),
    ]
