# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20171116_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='Producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='pagado',
        ),
        migrations.AddField(
            model_name='venta',
            name='Cliente',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
