# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_menu_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apePaterno', models.CharField(max_length=60)),
                ('apeMaterno', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(max_length=100)),
                ('maxPersonas', models.CharField(max_length=60)),
                ('numMesa', models.CharField(max_length=60)),
                ('libre', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.CharField(max_length=10)),
                ('confirmado', models.CharField(max_length=10)),
                ('servido', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cliente')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Menu')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
