# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20171116_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='Producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto'),
            preserve_default=False,
        ),
    ]
