# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_detalleventa_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='libre',
            field=models.CharField(max_length=60),
        ),
    ]
