# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_cliente_mesa_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=15)),
                ('precioUni', models.FloatField(default=0.0)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Menu')),
            ],
            options={
                'verbose_name': 'detalleMenu',
                'verbose_name_plural': 'detalleMenus',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizada', models.CharField(max_length=2)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cliente')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Mesa')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('precioTotal', models.FloatField(default=0.0)),
                ('servida', models.CharField(max_length=15)),
                ('pagado', models.CharField(max_length=15)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Menu')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
