# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_detallemenu_reserva_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='libre',
            field=models.BooleanField(default=True),
        ),
    ]
