# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20171105_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
